spring:
  profiles:
    active: local
    include: oauth, aws
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  devtools.livereload.enabled: true
  thymeleaf.cache: false

management:
  server:
    port: 8079
  endpoints:
    web:
      exposure:
        include: "*"
  endPoint:
    health:
      show-details: always
server:
  tomcat:
    mbeanregistry:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: market-collection-s3/items
    region:
      static: ap-northeast-2