spring:
  profiles:
    active: local
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/marketcollection?serverTimezone=Asia/Seoul
    username: mc_local
    password: mc123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  devtools.livereload.enabled: true
  thymeleaf.cache: false

logging.level:
  org.hibernate.SQL: debug

uploadPath: 'file:///D:/develop/resources/market-collection/'
itemImageLocation: 'D:/develop/resources/market-collection/items'